version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: postgres-16
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: local_db
      POSTGRES_PASSWORD: s3c73t-p4$$w07d
      POSTGRES_USER: postgres
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    build:
      context: ./
    container_name: backend
    image: backend
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
      DB_PORT: 5435
      DB_USERNAME: postgres
      DB_PASSWORD: 's3c73t-p4$$w07d'
      DB_NAME: local_db
      DB_HOST: "postgres-16"
    links:
      - postgres
  migration:
    build:
       context: ./
    command:
       [
        "./wait-for-it/wait-for-it.sh",
        "db:5435",
        "--",
        "npx",
        "sequelize-cli",
        "db:migrate"
       ]
    links:
      - postgres
    depends_on:
      - postgres
    env_file: .env
    environment:
      DB_HOST: "postgres-16"
      DB_USERNAME: postgres
      DB_PASSWORD: 's3c73t-p4$$w07d'
  frontend:
      build: ../schedule_decode_frontend
      container_name: frontend_c
      ports:
      - 3000:3000
      stdin_open: true
      tty: true
volumes:
  database: {}
